apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: camera
        image: charleestefanski/camera:latest
        securityContext:
          privileged: true
        env:
        - name: DISPLAY
          value: ':0'
        volumeMounts:
        - mountPath: /dev/video0
          name: video0
      volumes:
      - name: video0
        hostPath:
          path: /dev/video0
