apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: forwarder
        image: charleestefanski/mqtt-forwarder:latest
      - name: logs
        image: charleestefanski/logs:latest
